export default {
    language: {
        name: 'Deutsch'
    },
    main_fragment: {
        dashboard: 'Status',
        basic: 'Grundlegende Informationen',
        settings: 'Einstellungen',
    },
    bugreport: {
        export: 'Fehlerbericht exportieren',
        exporting: 'Exportieren…',
        export_success_title: 'Fehlerbericht exportiert',
        export_success: 'Der Fehlerbericht wurde gespeichert unter:',
        export_failed_title: 'Export fehlgeschlagen',
        export_failed: 'Der Export des Fehlerberichts ist fehlgeschlagen.',
        copy_path: 'Pfad kopieren',
        copy_path_failed: 'Kopieren fehlgeschlagen',
        send_log: 'Protokoll senden',
        send_failed: 'Senden fehlgeschlagen',
    },
    dashboard: {
        root_impl: 'Root-Implementierung',
        zygote_monitor: 'Zygote-Monitor',
        zygisk_module_title: 'Keine Zygisk-Module | Zygisk-Modul ({0}) | Zygisk-Module ({0})',
        zn_module_title: 'Keine ZN-Module | ZN-Modul ({0}) | ZN-Module ({0})',
        root_impl_normal: 'Aktuelle Root-Implementierung ist {impl}, die Denylist funktioniert ordnungsgemäß.',
        root_impl_abnormal: 'Root-Implementierung konnte nicht ermittelt werden, die Denylist funktioniert nicht.',
        root_impl_multiple: 'Es wurden mehrere Root-Implementierungen gefunden; die Denylist funktioniert nicht.',
        kernelsu_denylist: 'Die Denylist von KernelSU bezieht sich auf Apps, die im App-Profil als \'Module aushängen\' markiert sind.',
        magisk_denylist: 'Die Denylist von Magisk bezieht sich auf die integrierte Denylist von Magisk.',
        apatch_denylist: 'Die Denylist von APatch bezieht sich auf die SuperUser-App, bei der \'Ausschließen\' aktiviert ist und Root deaktiviert ist.',
    },
    settings: {
        log_to_kernel: 'Protokollierung in dmesg (nur für Entwickler)',
        nonroot_as_denylist: 'Nicht-Root-Apps als Denylist behandeln',
        enforce_denylist: 'Denylist-Richtlinie',
        enforce_denylist_desc: 'Erzwungen: Code-Injektion blockieren und Mount-Änderungen für Apps in der Denylist rückgängig machen.<br/>Nur Umount: Mount-Änderungen rückgängig machen, aber Code-Injektion für Apps in der Denylist zulassen.',
        enforce_denylist_alert: 'Für normale Benutzer wird dringend empfohlen, die Kernel-Umount-Funktion im KernelSU-Manager manuell zu deaktivieren, um zu vermeiden, dass Mountpunkte aufgrund von Fehlkonfigurationen mehrfach ausgehängt werden.',
        denylist_disabled: 'Deaktiviert',
        denylist_enforced: 'Erzwungen',
        denylist_just_umount: 'Nur Aushängen',
        anonymous_memory: 'Anonymen Speicher verwenden',
        anonymous_memory_desc: 'Module in den anonymen Speicher laden. Dies beeinträchtigt die Lesbarkeit der Protokolle, umgeht jedoch bestimmte veraltete Erkennungsmechanismen.',
        zn_linker: 'Zygisk Next-Linker verwenden',
        zn_linker_desc: 'Zum Laden von Modulen den integrierten Linker anstelle des System-Linkers verwenden. Dies verbessert die Tarnung, kann jedoch Kompatibilitätsprobleme verursachen.',
    },
    zygote_inject_state: {
        running: 'Läuft',
        stop_by_user: 'Vom Benutzer gestoppt',
        stop_by_crash: 'Durch Absturz von Zygote gestoppt',
        running_desc: 'Der Zygote-Monitor läuft normal.',
        stop_by_user_desc: 'Zygote-Monitor vom Benutzer gestoppt.',
        stop_by_crash_desc: 'Wiederholte Neustarts von Zygote wurden erkannt, der Zygote-Monitor wurde automatisch gestoppt.',
    },
    zygote_state: {
        unknown: 'Unbekannt',
        injected: 'Eingeschleust ({pid})',
        inject_failed: 'Einschleusen fehlgeschlagen ({pid})',
        skipped: 'Übersprungen ({pid})',
        abnormal: 'Anomal ({pid})',
        unknown_desc: 'Der Status dieses Zygote ist unbekannt; möglicherweise existiert er, wurde jedoch nicht gestartet, oder der Zygote-Monitor hat seinen Start nicht erkannt.',
        injected_desc: 'Zygisk wurde in den Zygote injiziert. Seine Prozess-ID lautet {pid}',
        inject_failed_desc: 'Es wurde versucht, Zygisk in diesen Zygote zu injizieren, was jedoch fehlgeschlagen ist. Seine Prozess-ID lautet {pid}',
        skipped_desc: 'Der Start der Zygote wurde überwacht. Ihre Prozess-ID lautet {pid}. Die Einbindung von Zygisk wurde jedoch aufgrund mehrerer vorheriger Soft-Neustarts des Systems gestoppt.',
        abnormal_desc: 'Zygisk wurde in den Zygote-Prozess {pid} eingebunden, aber der JNI-Hook hat keine passenden Methoden ({funcs}) gefunden, sodass Module nicht normal geladen werden. Möglicherweise handelt es sich um eine nicht unterstützte neue Version oder ein spezielles Android-System. Bitte erstelle ein Issue auf GitHub und stelle die Dateien /system/framework/framework.jar und /system/lib64/libandroid_runtime.so aus dem aktuellen System zur Verfügung, damit die Entwickler die Unterstützung hinzufügen können.',
    },
    corrupted: {
        title: 'Moduldateien sind beschädigt',
        desc: 'Bitte mache die Änderungen an Zygisk Next rückgängig und versuche es erneut.',
    },
    module: {
        issue: {
            title: 'Dieses Modul weist ein Problem auf',
            companion_api_issue: 'Dieses Modul {name} weist ein Problem bei der unsachgemäßen Verwendung der Companion-API auf, was zu Prozessabstürzen und Speicherlecks führen kann. Bitte wenden Sie sich an den Entwickler dieses Moduls, um das Problem zu beheben.',
            linker_issue: 'Dieses Modul {name} konnte nicht geladen werden. Bitte melden Sie das Problem dem Modulentwickler.',
            crash_issue: 'Dieses Modul {name} tauchte im Backtrace des Absturz-Threads von {processes} auf.',
            unknown_process: 'Unbekannter Prozess',
            learn_more: 'Weitere Informationen finden Sie hier: {link}',
            check_banner: 'Es wurden keine problematischen Module erkannt. | Das Modul {0} weist ein Problem auf. Bitte überprüfen Sie die Modulliste. | {0} Module weisen Probleme auf. Bitte überprüfen Sie die Modulliste.',
            badge: 'Problem',
            crash_badge: 'Absturz',
        },
        zn: {
            process_count: 'Kein Prozess | {0} Prozess | {0} Prozesse',
        },
    },
}
