export default {
    language: {
        name: 'Español (España)'
    },
    main_fragment: {
        dashboard: 'Estado',
        basic: 'Información básica',
        settings: 'Ajustes',
    },
    bugreport: {
        export: 'Exportar informe de error',
        exporting: 'Exportando…',
        export_success_title: 'Informe de error exportado',
        export_success: 'El informe de error se ha guardado en:',
        export_failed_title: 'Error en la exportación',
        export_failed: 'No se ha podido exportar el informe de error.',
        copy_path: 'Copiar ruta',
        copy_path_failed: 'Error al copiar',
        send_log: 'Enviar registro',
        send_failed: 'Error al enviar',
    },
    dashboard: {
        root_impl: 'Implementación de root',
        zygote_monitor: 'Zygote Monitor',
        zygisk_module_title: 'No hay módulos Zygisk | Módulo Zygisk ({0}) | Módulos Zygisk ({0})',
        zn_module_title: 'No hay módulos ZN | Módulo ZN ({0}) | Módulos ZN ({0})',
        root_impl_normal: 'La implementación de root actual es {impl}; la lista de exclusión funcionará correctamente.',
        root_impl_abnormal: 'No se ha podido determinar la implementación de root; la lista de exclusión no funcionará.',
        root_impl_multiple: 'Se han encontrado varias implementaciones de root; la lista de exclusión no funcionará.',
        kernelsu_denylist: 'La lista de exclusión de KernelSU se refiere a las aplicaciones marcadas como \'Desmontar módulos\' en el perfil de la aplicación.',
        magisk_denylist: 'La lista de exclusión de Magisk se refiere a la lista de exclusión integrada de Magisk.',
        apatch_denylist: 'La lista de exclusión de APatch se refiere a la aplicación SuperUser en la que está activada la opción \'Excluir\' y se desactiva el acceso root.',
    },
    settings: {
        log_to_kernel: 'Registro en dmesg (solo para desarrolladores)',
        nonroot_as_denylist: 'Tratar las aplicaciones sin root como si estuvieran en la lista de rechazo',
        enforce_denylist: 'Política de la lista de rechazo',
        enforce_denylist_desc: 'Aplicada: Bloquear la inyección de código y revertir las modificaciones de montaje para las aplicaciones de la lista de rechazo.<br/>Solo desmontaje: Revertir las modificaciones de montaje, pero permitir la inyección de código para las aplicaciones de la lista de rechazo.',
        enforce_denylist_alert: 'Para los usuarios normales, se recomienda encarecidamente desactivar manualmente la función de desmontaje del kernel en el gestor de KernelSU para evitar que los puntos de montaje se desmonten varias veces debido a una configuración incorrecta.',
        denylist_disabled: 'Desactivado',
        denylist_enforced: 'Aplicado',
        denylist_just_umount: 'Solo desmontaje',
        anonymous_memory: 'Usar memoria anónima',
        anonymous_memory_desc: 'Cargar módulos en memoria anónima. Esto compromete la legibilidad de los registros, pero elude ciertos mecanismos de detección obsoletos.',
        zn_linker: 'Usar el enlazador Zygisk Next',
        zn_linker_desc: 'Utilizar el enlazador integrado en lugar del enlazador del sistema para cargar módulos. Esto mejorará el sigilo, pero puede provocar problemas de compatibilidad.',
    },
    zygote_inject_state: {
        running: 'En ejecución',
        stop_by_user: 'Detenido por el usuario',
        stop_by_crash: 'Detenido por fallo de Zygote',
        running_desc: 'Zygote Monitor funciona con normalidad.',
        stop_by_user_desc: 'Zygote Monitor detenido por el usuario.',
        stop_by_crash_desc: 'Se han detectado reinicios repetidos de Zygote; Zygote Monitor se ha detenido automáticamente.',
    },
    zygote_state: {
        unknown: 'Desconocido',
        injected: 'Inyectado ({pid})',
        inject_failed: 'Fallo en la inyección ({pid})',
        skipped: 'Omitido ({pid})',
        abnormal: 'Anormal ({pid})',
        unknown_desc: 'Se desconoce el estado de este Zygote; puede que exista pero no se haya iniciado, o puede que Zygote Monitor no haya detectado su inicio.',
        injected_desc: 'Se ha inyectado Zygisk en el Zygote. Su ID de proceso es {pid}',
        inject_failed_desc: 'Se intentó inyectar Zygisk en este Zygote, pero falló. Su ID de proceso es {pid}',
        skipped_desc: 'Se ha supervisado el inicio del Zygote. Su ID de proceso es {pid}. Sin embargo, la inyección de Zygisk se detuvo debido a múltiples reinicios suaves previos del sistema.',
        abnormal_desc: 'Se ha inyectado Zygisk en el proceso Zygote {pid}, pero JNI Hook no ha encontrado métodos coincidentes ({funcs}), por lo que los módulos no se cargarán normalmente. Puede tratarse de una nueva versión no compatible o de un sistema Android especial. Por favor, crea una incidencia en GitHub y proporciona los archivos /system/framework/framework.jar y /system/lib64/libandroid_runtime.so del sistema actual para que los desarrolladores puedan añadir compatibilidad.',
    },
    corrupted: {
        title: 'Archivos del módulo dañados',
        desc: 'Por favor, revierte los cambios realizados en Zygisk Next e inténtalo de nuevo.',
    },
    module: {
        issue: {
            title: 'Este módulo presenta un problema',
            companion_api_issue: 'Este módulo {name} presenta un problema relacionado con un uso incorrecto de la API Companion, lo que puede provocar fallos en los procesos y fugas de memoria. Ponte en contacto con el desarrollador de este módulo para resolver el problema.',
            linker_issue: 'No se ha podido cargar este módulo {name}. Informa del problema al desarrollador del módulo.',
            crash_issue: 'Este módulo {name} apareció en el backtrace del hilo que falló de: {processes}.',
            unknown_process: 'Proceso desconocido',
            learn_more: 'Visita esta página para obtener más información: {link}',
            check_banner: 'No se han detectado módulos problemáticos. | El módulo {0} presenta un problema. Revisa la lista de módulos. | {0} módulos presentan problemas. Revisa la lista de módulos.',
            badge: 'Problema',
            crash_badge: 'Fallo',
        },
        zn: {
            process_count: 'Ningún proceso | {0} proceso | {0} procesos',
        },
    },
}
