export default {
    language: {
        name: 'Italiano'
    },
    main_fragment: {
        dashboard: 'Stato',
        basic: 'Informazioni di base',
        settings: 'Impostazioni',
    },
    bugreport: {
        export: 'Esporta segnalazione di bug',
        exporting: 'Esportazione in corso…',
        export_success_title: 'Segnalazione di bug esportata',
        export_success: 'La segnalazione di bug è stata salvata in:',
        export_failed_title: 'Esportazione non riuscita',
        export_failed: 'Impossibile esportare la segnalazione di bug.',
        copy_path: 'Copia percorso',
        copy_path_failed: 'Copia non riuscita',
        send_log: 'Invia log',
        send_failed: 'Invio non riuscito',
    },
    dashboard: {
        root_impl: 'Implementazione root',
        zygote_monitor: 'Zygote Monitor',
        zygisk_module_title: 'Nessun modulo Zygisk | Modulo Zygisk ({0}) | Moduli Zygisk ({0})',
        zn_module_title: 'Nessun modulo ZN | Modulo ZN ({0}) | Moduli ZN ({0})',
        root_impl_normal: 'L\'attuale implementazione root è {impl}, la lista di esclusione funzionerà correttamente.',
        root_impl_abnormal: 'Impossibile determinare l\'implementazione root, la lista di esclusione non funzionerà.',
        root_impl_multiple: 'Trovate più implementazioni di root; la lista di esclusione non funzionerà.',
        kernelsu_denylist: 'La lista di esclusione di KernelSU si riferisce alle app contrassegnate come \'Moduli da smontare\' nel profilo dell\'app.',
        magisk_denylist: 'La lista di esclusione di Magisk si riferisce alla lista di esclusione integrata di Magisk.',
        apatch_denylist: 'La lista di esclusione di APatch si riferisce all\'app SuperUser in cui è abilitata l\'opzione \'Escludi\' e il root è disabilitato',
    },
    settings: {
        log_to_kernel: 'Registra su dmesg (solo per sviluppatori)',
        nonroot_as_denylist: 'Tratta le app non root come se fossero nella lista di esclusione',
        enforce_denylist: 'Politica della lista di esclusione',
        enforce_denylist_desc: 'Applicata: blocca l\'iniezione di codice e ripristina le modifiche di montaggio per le app nella lista di esclusione.<br/>Solo smontaggio: ripristina le modifiche di montaggio ma consente l\'iniezione di codice per le app nella lista di esclusione.',
        enforce_denylist_alert: 'Per gli utenti normali, si raccomanda vivamente di disabilitare manualmente la funzione di smontaggio del kernel nel gestore KernelSU per evitare che i punti di montaggio vengano smontati più volte a causa di una configurazione errata.',
        denylist_disabled: 'Disabilitato',
        denylist_enforced: 'Applicato',
        denylist_just_umount: 'Solo smontaggio',
        anonymous_memory: 'Usa memoria anonima',
        anonymous_memory_desc: 'Carica i moduli nella memoria anonima. Ciò compromette la leggibilità dei log ma aggira alcuni meccanismi di rilevamento obsoleti.',
        zn_linker: 'Usa il linker Zygisk Next',
        zn_linker_desc: 'Utilizza il linker integrato anziché quello di sistema per caricare i moduli. Ciò migliorerà la furtività ma potrebbe causare problemi di compatibilità.',
    },
    zygote_inject_state: {
        running: 'In esecuzione',
        stop_by_user: 'Arrestato dall\'utente',
        stop_by_crash: 'Arrestato a causa di un crash di Zygote',
        running_desc: 'Zygote Monitor funziona normalmente.',
        stop_by_user_desc: 'Zygote Monitor arrestato dall\'utente.',
        stop_by_crash_desc: 'Sono stati rilevati riavvii ripetuti di Zygote; Zygote Monitor si è arrestato automaticamente.',
    },
    zygote_state: {
        unknown: 'Sconosciuto',
        injected: 'Inserito ({pid})',
        inject_failed: 'Inserimento fallito ({pid})',
        skipped: 'Saltato ({pid})',
        abnormal: 'Anomalo ({pid})',
        unknown_desc: 'Lo stato di questo Zygote è sconosciuto: potrebbe esistere ma non essere avviato, oppure Zygote Monitor potrebbe non averne rilevato l\'avvio.',
        injected_desc: 'Zygisk è stato iniettato nello Zygote. Il suo ID di processo è {pid}',
        inject_failed_desc: 'Si è tentato di iniettare Zygisk in questo Zygote, ma l\'operazione non è andata a buon fine. Il suo ID di processo è {pid}',
        skipped_desc: 'È stato rilevato l\'avvio dello Zygote. Il suo ID di processo è {pid}. Tuttavia, l\'iniezione di Zygisk è stata interrotta a causa di precedenti riavvii software multipli del sistema.',
        abnormal_desc: 'Zygisk è stato iniettato nel processo Zygote {pid}, ma JNI Hook non ha trovato metodi corrispondenti ({funcs}), pertanto i moduli non verranno caricati normalmente. Potrebbe trattarsi di una nuova versione non supportata o di un sistema Android speciale. Si prega di creare un ticket su GitHub e fornire i file /system/framework/framework.jar e /system/lib64/libandroid_runtime.so dal sistema attuale, in modo che gli sviluppatori possano aggiungere il supporto.',
    },
    corrupted: {
        title: 'File dei moduli danneggiati',
        desc: 'Si prega di annullare le modifiche apportate a Zygisk Next e riprovare.',
    },
    module: {
        issue: {
            title: 'Questo modulo presenta un problema',
            companion_api_issue: 'Questo modulo {name} presenta un problema legato a un uso improprio dell\'API Companion, che potrebbe causare arresti anomali del processo e perdite di memoria. Contatta lo sviluppatore di questo modulo per risolvere il problema.',
            linker_issue: 'Impossibile caricare questo modulo {name}. Segnala il problema allo sviluppatore del modulo.',
            crash_issue: 'Questo modulo {name} è apparso nel backtrace del thread che ha causato l\'arresto anomalo di: {processes}.',
            unknown_process: 'processo sconosciuto',
            learn_more: 'Per ulteriori informazioni, visita questa pagina: {link}',
            check_banner: 'Nessun modulo problematico rilevato. | Il modulo {0} presenta un problema. Controlla l\'elenco dei moduli. | {0} moduli presentano problemi. Controlla l\'elenco dei moduli.',
            badge: 'Problema',
            crash_badge: 'Arresto anomalo',
        },
        zn: {
            process_count: 'Nessun processo | {0} processo | {0} processi',
        },
    },
}
