export default {
    language: {
        name: '한국어'
    },
    main_fragment: {
        dashboard: '상태',
        basic: '기본 정보',
        settings: '설정',
    },
    bugreport: {
        export: '버그 보고서 내보내기',
        exporting: '내보내기 중…',
        export_success_title: '버그 보고서 내보내기 완료',
        export_success: '버그 보고서가 다음 위치에 저장되었습니다:',
        export_failed_title: '내보내기 실패',
        export_failed: '버그 보고서 내보내기에 실패했습니다.',
        copy_path: '경로 복사',
        copy_path_failed: '복사 실패',
        send_log: '로그 전송',
        send_failed: '전송 실패',
    },
    dashboard: {
        root_impl: '루트 구현',
        zygote_monitor: 'Zygote 모니터',
        zygisk_module_title: 'Zygisk 모듈 없음 | Zygisk 모듈 ({0}) | Zygisk 모듈 ({0})',
        zn_module_title: 'ZN 모듈 없음 | ZN 모듈 ({0}) | ZN 모듈 ({0})',
        root_impl_normal: '현재 루트 구현은 {impl}이며, 차단 목록이 정상적으로 작동합니다.',
        root_impl_abnormal: '루트 구현을 확인할 수 없으므로, 차단 목록이 작동하지 않습니다.',
        root_impl_multiple: '여러 루트 구현이 발견되었습니다. 차단 목록이 작동하지 않습니다.',
        kernelsu_denylist: 'KernelSU의 차단 목록은 앱 프로필에서 \'모듈 마운트 해제\'로 표시된 앱을 의미합니다.',
        magisk_denylist: 'Magisk의 차단 목록은 Magisk의 내장 차단 목록을 의미합니다.',
        apatch_denylist: 'APatch의 차단 목록은 \'제외\'가 활성화되어 있고 루트 권한이 비활성화된 SuperUser 앱을 의미합니다.',
    },
    settings: {
        log_to_kernel: 'dmesg에 기록 (개발자 전용)',
        nonroot_as_denylist: '비루트 앱을 차단 목록으로 취급',
        enforce_denylist: '차단 목록 정책',
        enforce_denylist_desc: '강제 적용: 차단 목록에 포함된 앱에 대해 코드 주입을 차단하고 마운트 변경 사항을 원상 복구합니다.<br/>마운트 해제 전용: 차단 목록에 포함된 앱에 대해 마운트 변경 사항을 원상 복구하되 코드 주입은 허용합니다.',
        enforce_denylist_alert: '일반 사용자의 경우, 잘못된 구성으로 인해 마운트 지점이 여러 번 언마운트되는 것을 방지하기 위해 KernelSU 관리자에서 커널 언마운트 기능을 수동으로 비활성화할 것을 강력히 권장합니다.',
        denylist_disabled: '비활성화됨',
        denylist_enforced: '강제 적용',
        denylist_just_umount: '언마운트 전용',
        anonymous_memory: '익명 메모리 사용',
        anonymous_memory_desc: '모듈을 익명 메모리에 로드합니다. 이로 인해 로그 가독성이 저하되지만, 특정 구식 탐지 메커니즘을 우회할 수 있습니다.',
        zn_linker: 'Zygisk Next 링커 사용',
        zn_linker_desc: '모듈을 로드할 때 시스템 링커 대신 내장 링커를 사용합니다. 이는 은밀성을 높여주지만 호환성 문제를 일으킬 수 있습니다.',
    },
    zygote_inject_state: {
        running: '실행 중',
        stop_by_user: '사용자에 의해 중지됨',
        stop_by_crash: 'Zygote 크래시 발생으로 중지',
        running_desc: 'Zygote 모니터가 정상적으로 실행 중입니다.',
        stop_by_user_desc: 'Zygote 모니터가 사용자에 의해 중지되었습니다.',
        stop_by_crash_desc: 'Zygote의 반복적인 재시작이 감지되어 Zygote 모니터가 자동으로 중지되었습니다.',
    },
    zygote_state: {
        unknown: '알 수 없음',
        injected: '주입됨 ({pid})',
        inject_failed: '주입 실패 ({pid})',
        skipped: '건너뜀 ({pid})',
        abnormal: '비정상 ({pid})',
        unknown_desc: '이 Zygote의 상태는 알 수 없으며, 존재할 수는 있으나 시작되지 않았거나, Zygote 모니터가 시작을 감지하지 못했을 수 있습니다.',
        injected_desc: 'Zygisk가 Zygote에 주입되었습니다. 해당 프로세스 ID는 {pid}입니다.',
        inject_failed_desc: '이 Zygote에 Zygisk를 주입하려고 시도했으나 실패했습니다. 해당 프로세스 ID는 {pid}입니다.',
        skipped_desc: 'Zygote가 시작된 것으로 모니터링되었습니다. 해당 프로세스 ID는 {pid}입니다. 하지만 이전에 시스템이 여러 번 소프트 재부팅된 탓에 Zygisk 주입이 중단되었습니다.',
        abnormal_desc: 'Zygisk가 Zygote 프로세스 {pid}에 주입되었으나, JNI Hook이 일치하는 메서드({funcs})를 찾지 못했기 때문에 모듈이 정상적으로 로드되지 않습니다. 이는 지원되지 않는 새 버전이나 특수한 Android 시스템 때문일 수 있습니다. GitHub에 이슈를 등록하고, 개발자가 지원을 추가할 수 있도록 현재 시스템의 /system/framework/framework.jar 및 /system/lib64/libandroid_runtime.so 파일을 제공해 주십시오.',
    },
    corrupted: {
        title: '모듈 파일이 손상되었습니다.',
        desc: 'Zygisk Next에 대한 변경 사항을 되돌린 후 다시 시도해 주십시오.',
    },
    module: {
        issue: {
            title: '이 모듈에 문제가 있습니다',
            companion_api_issue: '이 모듈 {name}은 Companion API를 부적절하게 사용하여 프로세스 충돌 및 메모리 누수를 유발할 수 있는 문제가 있습니다. 문제 해결을 위해 해당 모듈 개발자에게 문의해 주십시오.',
            linker_issue: '이 모듈 {name}을(를) 로드하지 못했습니다. 모듈 개발자에게 문제를 보고해 주십시오.',
            crash_issue: '이 모듈 {name}이(가) {processes}의 충돌 스레드 백트레이스에 나타났습니다.',
            unknown_process: '알 수 없는 프로세스',
            learn_more: '자세한 정보는 여기를 참조하십시오: {link}',
            check_banner: '문제가 있는 모듈이 감지되지 않았습니다. | {0}개의 모듈에 문제가 있습니다. 모듈 목록을 확인해 주십시오. | {0}개의 모듈에 문제가 있습니다. 모듈 목록을 확인해 주십시오.',
            badge: '문제',
            crash_badge: '충돌',
        },
        zn: {
            process_count: '프로세스 없음 | {0}개의 프로세스 | {0}개의 프로세스',
        },
    },
}
